---
- name: AWS Bootstrap
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    vpc_name:         "{{ project_name }}-{{ project_environment }}-vpc-main-bootstrap"
    sg_test_name:     "{{ project_name }}-{{ project_environment }}-sg-test-bootstrap"
    sg_natgw_name:    "{{ project_name }}-{{ project_environment }}-sg-natgw-bootstrap"
    instance_natgw_name: "{{ project_name }}-{{ project_environment }}-ec2-natgw-bootstrap"
    public_rt_name:   "{{ project_name }}-{{ project_environment }}-rt-public-bootstrap"
    private_rt_name:  "{{ project_name }}-{{ project_environment }}-rt-private-bootstrap"
    nat_rt_name:      "{{ project_name }}-{{ project_environment }}-rt-nat-bootstrap"
    role_name:        "{{ project_name }}-{{ project_environment }}-role-main-bootstrap"
    policy_name:      "{{ project_name }}-{{ project_environment }}-policy-main-bootstrap"
    s3_name:          "{{ project_name }}-{{ project_environment }}-s3-main-bootstrap"
    keypair_name:     "{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap"
    keypair_file:     "{{ lookup('env', 'HOME') }}/{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap.pem"
  tasks:
    - name: Ensure GitHub Actions OIDC provider exists
      community.aws.aws_iam_openid_connect_provider:
        url: "https://token.actions.githubusercontent.com"
        client_id_list:
          - "sts.amazonaws.com"
        thumbprint_list:
          - "6938fd4d98bab03faadb97b34396831e3780aea1"
        state: present
      register: oidc_provider_result

    - name: Show OIDC provider status
      debug:
        var: oidc_provider_result
