---
- name: AWS Bootstrap
  hosts: localhost
  gather_facts: no
  collections:
    - community.aws
  vars:
    vpc_name:         "{{ project_name }}-{{ project_environment }}-vpc-main-bootstrap"
    sg_test_name:     "{{ project_name }}-{{ project_environment }}-sg-test-bootstrap"
    sg_natgw_name:    "{{ project_name }}-{{ project_environment }}-sg-natgw-bootstrap"
    instance_natgw_name: "{{ project_name }}-{{ project_environment }}-ec2-natgw-bootstrap"
    public_rt_name:   "{{ project_name }}-{{ project_environment }}-rt-public-bootstrap"
    private_rt_name:  "{{ project_name }}-{{ project_environment }}-rt-private-bootstrap"
    nat_rt_name:      "{{ project_name }}-{{ project_environment }}-rt-nat-bootstrap"
    role_name:        "{{ project_name }}-{{ project_environment }}-role-main-bootstrap"
    policy_name:      "{{ project_name }}-{{ project_environment }}-policy-main-bootstrap"
    s3_name:          "{{ project_name }}-{{ project_environment }}-s3-main-bootstrap"
    keypair_name:     "{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap"
    keypair_file:     "{{ lookup('env', 'HOME') }}/{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap.pem"
  tasks:
    - name: Mostrar variables de configuración y nombres generados
      debug:
        msg: |
          # Variables del archivo JSON
          project_name            = {{ project_name }}
          project_environment     = {{ project_environment }}
          vpc_cidr                = {{ vpc_cidr }}
          vpc_ipv6                = {{ vpc_ipv6 }}
          vpc_subnet_nat          = {{ vpc_subnet_nat }}
          hostedzones_public      = {{ hostedzones_public }}
          hostedzones_private     = {{ hostedzones_private }}
          vpc_subnet_nat_tskey    = {{ vpc_subnet_nat_tskey }}
          github_account          = {{ github_account }}
          github_repo             = {{ github_repo }}

          # Nombres generados
          vpc_name                = {{ vpc_name }}
          sg_test_name            = {{ sg_test_name }}
          sg_natgw_name           = {{ sg_natgw_name }}
          instance_natgw_name     = {{ instance_natgw_name }}
          public_rt_name          = {{ public_rt_name }}
          private_rt_name         = {{ private_rt_name }}
          nat_rt_name             = {{ nat_rt_name }}
          role_name               = {{ role_name }}
          policy_name             = {{ policy_name }}
          s3_name                 = {{ s3_name }}
          keypair_name            = {{ keypair_name }}
          keypair_file            = {{ keypair_file }}
