---
- name: AWS Bootstrap
  hosts: localhost
  gather_facts: no
  vars:
    vpc_name:         "{{ project_name }}-{{ project_environment }}-vpc-main-bootstrap"
    sg_test_name:     "{{ project_name }}-{{ project_environment }}-sg-test-bootstrap"
    sg_natgw_name:    "{{ project_name }}-{{ project_environment }}-sg-natgw-bootstrap"
    instance_natgw_name: "{{ project_name }}-{{ project_environment }}-ec2-natgw-bootstrap"
    public_rt_name:   "{{ project_name }}-{{ project_environment }}-rt-public-bootstrap"
    private_rt_name:  "{{ project_name }}-{{ project_environment }}-rt-private-bootstrap"
    nat_rt_name:      "{{ project_name }}-{{ project_environment }}-rt-nat-bootstrap"
    role_name:        "{{ project_name }}-{{ project_environment }}-role-main-bootstrap"
    policy_name:      "{{ project_name }}-{{ project_environment }}-policy-main-bootstrap"
    s3_name:          "{{ project_name }}-{{ project_environment }}-s3-main-bootstrap"
    keypair_name:     "{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap"
    keypair_file:     "{{ lookup('env', 'HOME') }}/{{ project_name }}-{{ project_environment }}-keypair-main-bootstrap.pem"
  tasks:
    - name: Get AWS account
      amazon.aws.aws_caller_info:
      register: caller_account
    - name: OIDC IAM Role Policy
      set_fact:
        policy_role_oidc: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::{{ caller_account.account }}:oidc-provider/token.actions.githubusercontent.com"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:{{ github_account }}/{{ github_repo }}:*"
                  }
                }
              }
            ]
          }
    - name: OIDC IAM Role
      amazon.aws.iam_role:
        name: "{{ role_name }}"
        assume_role_policy_document: "{{ policy_role_oidc }}"
        state: present